## Customize the test machine
version: 2
workflows:
  version: 2
  build:
    jobs:
      - python36
      - python27

jobs:
  python36: &test-template
    docker:
    - image: circleci/python:3.6
    working_directory: ~/ahay/src
    parallelism: 1
    #shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - checkout

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    - run: 
        name: Install Packages
        command: |
          sudo apt-get install python-pip
          sudo pip install numpy scipy
          sudo apt-get install libblas-dev liblapack-dev swig

    - run:
        name: Setup Environment Variables
        command: |
          echo 'export RSFROOT="$HOME/RSFROOT"'      >> $BASH_ENV
          echo 'export RSFFIGS="$HOME/RSFROOT/figs"' >> $BASH_ENV
    
    - run: 
        name: Checkout figs
        command : |
          git clone --depth 1 https://github.com/ahay/figs.git $RSFFIGS    

    - run: 
        name: Compile
        command: |
          ./configure 
          make install 
          source env.sh

    - run: 
        name: Test
        command: |
          source env.sh 
          cd book 
          scons test
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts

  python27:
    <<: *test-template
    docker:
    - image: circleci/python:2.7
